import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <nav className="bg-gray-800 p-4">
            <div className="container mx-auto flex justify-between">
              <Link href="/" className="text-white text-lg font-bold">
                Home
              </Link>
              <div className="space-x-4">
                <Link href="/healthcheck" className="text-gray-300 hover:text-white">
                  Health Check
                </Link>
                <Link href="/usuarios" className="text-gray-300 hover:text-white">
                  Users
                </Link>
                <Link href="/lojas" className="text-gray-300 hover:text-white">
                  Stores
                </Link>
                <Link href="/produtos" className="text-gray-300 hover:text-white">
                  Products
                </Link>
                <Link href="/ofertas" className="text-gray-300 hover:text-white">
                  Offers
                </Link>
              </div>
            </div>
          </nav>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
